### ISSUE TITLE
Enums in dashed strings

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-incrementor#2]
> Taken from original repo

I have setup a new enum that would be really useful for CSS box model properties:

```json
[
	"top",
	"right",
	"bottom",
	"left"
]
```

It works only if used in directly matching properties like:

```css
.someClass {
	position: relative;
	top: 3px;
}
```

Putting the cursor on the `top` property, and hitting the shortcut will cycle as expected.
However I would love if it could work for the other ton of css properties that have these positional properties in their name. Here are some examples:

```css
.someClass {
	border-bottom: 1px solid black;
	margin-left: 5px;
	padding-right: 10px;
	...
}
```

There are loads of these and it would be super useful to be able to quickly switch the direction using your extension.

From what I read, an enum value cannot start with a `-` so it means I can't create another enum like so:

```json
[
	"-top",
	"-right",
	"-bottom",
	"-left"
]
```
